name: Node.js CI

on:
    workflow_call:
        inputs:
            NODE_VERSION:
                required: true
                type: string
            WORKSPACE_CACHE_KEY:
                required: true
                type: string
            REF:
                required: true
                type: string

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.REF }}

            - name: Use Node.js ${{ inputs.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ inputs.NODE_VERSION }}

            - name: Cache node modules
              id: npm-cache
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm ci --legacy-peer-deps

            - name: Copy FE env
              run: cp .env.example .env

            - name: Build
              run: npm run build

            - name: Cache repository
              uses: actions/cache@v4
              with:
                  path: ${{ github.workspace }}
                  key: ${{ inputs.WORKSPACE_CACHE_KEY }}

    lint:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Restore cached repository
              uses: actions/cache/restore@v4
              with:
                  path: ${{ github.workspace }}
                  key: ${{ inputs.WORKSPACE_CACHE_KEY }}

            - name: Check lint
              run: npm run lint

    license:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Restore cached repository
              uses: actions/cache/restore@v4
              with:
                  path: ${{ github.workspace }}
                  key: ${{ inputs.WORKSPACE_CACHE_KEY }}

            - name: Run license checker
              run: npm run licence:check
