name: Deploy react intro to gcp

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      NODE_VERSION: 20.x
      WORKSPACE_CACHE_KEY: workspace-${{ github.run_id }}
      REF: ${{ github.sha }}
  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      ENVIRONMENT: main
      REGION: europe-west1
      PROJECT: river-span-433408-b2
      IMAGE: europe-west1-docker.pkg.dev/river-span-433408-b2/react-app-engine/react-app-engine
      PROJECT_NAME: react-app-engine
      API_ROUTE: https://river-span-433408-b2.ey.r.appspot.com
